theme: jekyll-theme-time-machine

permalink:
    /404.html

    normal.html

    first_chapter/first_point.html
    first_chapter/second_point.html
    first_chapter/third_point.html
    first_chapter/fourth_point.html

    second_chapter/first_point.html

